/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Frames;

import Presentation.Components.TabView;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Niels
 */
public class AdministrationPanel extends javax.swing.JPanel {

    TabView tv;
    EmployeeAdministrationPanel eap;
    CarAdministrationPanel vap;
    JFrame parent;

    /**
     * Creates new form AdministrationPanel
     */
    public AdministrationPanel(JFrame parent) {
        this.parent = parent;
        initComponents();

        tv = new TabView();
        eap = new EmployeeAdministrationPanel(parent);
        vap = new CarAdministrationPanel(parent);
        tv.addNewTab("Medarbejder", eap);
        tv.addNewTab("Biler", vap);

        add(tv, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
