/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Frames;

import BE.Message;
import BLL.Message_AccessLink;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Niels Kristian Ravn
 */
public class MessagePanel extends javax.swing.JPanel {

    MessageTableModel mtm;
    Message_AccessLink mal;

    /**
     * Creates new form MessagePanel
     */
    public MessagePanel() {
        try {
            mal = new Message_AccessLink();
        } catch (IOException ex) {
        }
        initComponents();
        mtm = new MessageTableModel(this);
        tblMessages.setModel(mtm);
        TableColumn tc = tblMessages.getColumnModel().getColumn(1);
        tc.setMaxWidth(100);
        ListSelectionModel lsm = tblMessages.getSelectionModel();
        lsm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbVisArkiverede = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnNewMessage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        cbVisArkiverede.setText("Vis arkiverede beskeder");
        cbVisArkiverede.setToolTipText("");
        cbVisArkiverede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVisArkiveredeActionPerformed(evt);
            }
        });
        jPanel1.add(cbVisArkiverede);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNewMessage.setText("Ny besked");
        btnNewMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMessageActionPerformed(evt);
            }
        });
        jPanel3.add(btnNewMessage);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMessages);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbVisArkiveredeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVisArkiveredeActionPerformed
        search();
    }//GEN-LAST:event_cbVisArkiveredeActionPerformed

    private void btnNewMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMessageActionPerformed
        createNewMessage();
    }//GEN-LAST:event_btnNewMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewMessage;
    private javax.swing.JCheckBox cbVisArkiverede;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMessages;
    // End of variables declaration//GEN-END:variables

    /**
     * searches for messages from the archived status set in the checkbox.
     */
    public void search() {
        boolean archived = cbVisArkiverede.isSelected();
        ArrayList<Message> messages = new ArrayList<>();
        try {
            messages = mal.getMessagesByArchivedStatus(archived);
        } catch (SQLException ex) {
        }
        mtm.setMessages(messages);
    }

    /**
     * creates a new message in the database and searches again to get the new one into the table.
     */
    private void createNewMessage() {
        try {
            mal.createNewMessage();
        } catch (SQLException ex) {
        }
        search();
    }

}
