/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Frames;

import BE.Alarm;
import BE.TimeSheet;
import BLL.Alarm_AccessLink;
import BLL.TimeSheet_AccessLink;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Susanne
 */
public class ShowUpList extends javax.swing.JPanel {

    Alarm_AccessLink aal;
    TimeSheet_AccessLink tsal;
    TableModelFiremanByCar tableFiremanByCar;
    int alarmID;
    final String stationsVagt = "Stationsvagt";
    /**
     * Creates new form ShowUpList
     */
    public ShowUpList() {
        try {
            aal = new Alarm_AccessLink();
            tsal = new TimeSheet_AccessLink();
        } catch (IOException ex) {
            Logger.getLogger(ShowUpList.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
        cbxCar.addActionListener(new myComboBoxSelectionListener());
        tableFiremanByCar = new TableModelFiremanByCar();
        tblShowUpOnCar.setModel(tableFiremanByCar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowUpOnCar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBil = new javax.swing.JLabel();
        cbxCar = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnApprove = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tblShowUpOnCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblShowUpOnCar);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblBil.setText("Bil :");
        jPanel1.add(lblBil);

        cbxCar.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(cbxCar);

        jPanel3.add(jPanel1, java.awt.BorderLayout.WEST);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnApprove.setText("Godkend");
        jPanel2.add(btnApprove, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JComboBox cbxCar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBil;
    private javax.swing.JTable tblShowUpOnCar;
    // End of variables declaration//GEN-END:variables

    void SelectionChanged(Alarm alarm) throws SQLException {
        cbxCar.removeAllItems();
        ArrayList<Integer> cars = new ArrayList<>();
        alarmID = alarm.getID();
        cars.addAll(aal.getCarNrByAlarmID(alarmID));
        for (Integer i : cars) {
            if(i == 0)
                cbxCar.addItem(stationsVagt);
            else
            cbxCar.addItem(i);
        }
    }

    private class myComboBoxSelectionListener implements ActionListener {
        ArrayList <TimeSheet> employees = new ArrayList<>();
        @Override
        public void actionPerformed(ActionEvent e) {
            int selectedCar = cbxCar.getSelectedIndex();
            if(cbxCar.getSelectedItem() != null && !cbxCar.getSelectedItem().equals(stationsVagt)){
                try {
                    employees = tsal.getTimeSheetByCarNrAndAlarmID(alarmID, ((int)cbxCar.getSelectedItem()) );
                } catch (SQLException ex) {
                    Logger.getLogger(ShowUpList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(cbxCar.getSelectedItem() != null){
                try {
                    employees = tsal.getTimeSheetByCarNrAndAlarmID(alarmID, 0 );
                } catch (SQLException ex) {
                    Logger.getLogger(ShowUpList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            tableFiremanByCar.setTimeSheets(employees);
            
        }

    }

}
